### ISSUE TITLE
[feature request] Support System.Text.Json as alternative to Newtonsoft.Json

### ISSUE THREAD

**Issue by Tyler-IN** [tryAGI/AutoSDK#20]
Instead of this,
```c#
var content = await response.Content.ReadAsStringAsync().ConfigureAwait(false);

return
  global::Newtonsoft.Json.JsonConvert.DeserializeObject<...>(content) ??
  throw new global::System.InvalidOperationException("Response deserialization failed for
```
Always read as a stream async and feed into [`JsonSerializer.DeserializeAsync<TValue>`](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer.deserializeasync).

This avoids multiple copy and conversion operations and continues the async pattern.
(Buffer construction [eg. stream buffer grown to fit then copied to single solid buffer], UTF-16 char copying conversion into string, then deserialization converting UTF-16 into various types.)

This would add a dependency on MS's System.Text.Json package.
Support goes down to .NET Standard 2.0.

**Comment by HavenDV** [comment]
yes, I agree with this. I didn't implement this as the default solution because the current solution allows for much easier debugging when the server sends something other than the expected json. in this case, an exception is completely uninformative.
Ideally I would implement your suggestion, but so that there are no problems with debugging
